### ISSUE TITLE
Define allowed/denied lints in root-level lints.toml instead of redundantly for every crate

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#1028]
We should do what the title says once the feature becomes available (one day):

https://github.com/rust-lang/cargo/issues/5034 (read "Motivations" section)

We could consider re-using the `lints.toml` file across repositories as it is currently a pain to maintain the same list of lints in so many places.

**Comment by joshuef** [comment]
going to close this as we've shifted over to a monorepo: https://github.com/maidsafe/safe_network
