### ISSUE TITLE
Rename error types and provide `Result` type for the crates

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#1066]
1. `CoreError`, `AuthError` and `AppError` can be renamed to just `Error` within the crates. This change will reduce some unnecessary verbosity. See [this issue](https://github.com/maidsafe/safe-api/issues/276) in safe-cli where we already implemented this renaming.
2. We can introduce `Result` to these crates which would be something like:

```rust
pub type Result<T> = Result<T, Error>;
```

where `Error` is the shortened name for the error type for the crate. This can further reduce verbosity because we currently have a lot of lines like:

```rust
    pub fn send<F>(&self, f: F) -> Result<(), AuthError>
```

which can become:

```rust
    pub fn send<F>(&self, f: F) -> Result<()>
```

etc.

When importing `safe_core::Error` from one of the other crates, then we can refer to it as `safe_core::Error` or `CoreError`, but it doesn't make sense to do so from within `safe_core` itself.

**Comment by S-Coyle** [comment]
Closing - no longer any `CoreError`, `AuthError` or `AppError`
