### ISSUE TITLE
Support recursive bootstrap and join

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/sn_client#1075]
The bootstrap process for clients in SCL need to be similar to the nodes bootstrap process:
1. Client starts looking for a destination section with client handlers managing it (XorName derived from its public ID),
2. Client bootstraps to any 1 node from its hard-coded contacts list,
3. If the node that we've bootstrapped to does not belong to the destination section, it shall return contacts for a known neighbouring section nearest to the destination,
4. Client attempts to bootstrap to nodes from the nearest section. If it is not the destination section again, repeat step 3.
5. Once the destination sections is reached, retrieve the list of elders in the section.
6. Complete the bootstrap process and join the section as a client.

The obtained contact information can be cached by the client.

**Comment by joshuef** [comment]
this is done :+1:
