### ISSUE TITLE
Clean up GitHub Actions workflows

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#1087]
1. We currently duplicate build jobs between the PR and Master workflows. We did this because we didn't know any other way of reusing parts of workflows. We could potentially do this by refactoring the entire build job into a script.

2. The `deploy` and `publish` jobs should only run if the last commit was a version change. Unfortunately this check doesn't work at the job-level, and so we had to add it to every single step of these jobs. This should be avoided, if possible. (We could do something like have a single step that fails if the last commit was not a version change, but this would fail the job and, by extension, the entire build.)

**Comment by m-cat** [comment]
For (2) we can use a job-level `if` to condition on a script which returns a boolean, deciding whether the job should run or not.

**Comment by m-cat** [comment]
Further information for (2):

Thread: https://github.community/t5/GitHub-Actions/Use-a-job-level-conditional-if-to-check-command-output/m-p/42911/highlight/false#M5170

Example PR: https://github.com/maidsafe/safe_client_libs/pull/1140

**Comment by S-Coyle** [comment]
Point (2) now addressed with use of `if` statements.

**Comment by joshuef** [comment]
going to close this as we've shifted over to a monorepo: https://github.com/maidsafe/safe_network
