### ISSUE TITLE
Replace deprecated AWS actions

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#1108]
The [aws repo](https://github.com/actions/aws) has a deprecation message, which also appears as a warning when running the action.

However, the [link given](https://github.com/aws-actions) does not provide an alternative.

The deadline given for moving from the old action in December 31, and this must be done for all our repos where we use the aws action.

**Comment by m-cat** [comment]
Reopening for our other crates where we use this:

- safe_vault
- safe-api

**Comment by S-Coyle** [comment]
Closing - nowhere now using deprecated aws action.
