### ISSUE TITLE
Implement Caveats and `Client Handling` verifiers

### ISSUE THREAD

**Issue by joshuef** [maidsafe/sn_client#1129]
Caveats are arbitrary string entries to be optionally verified at various stages of the request.

A suggested implementation would be to follow [macroon style verifiers](https://github.com/deislabs/rusty-macaroon/blob/master/examples/first_party.rs#L19-L44) .

We should verify caveats as needed while converting our permission check to tokens.

- [x] Implement a basic 'verifier' for tokens.
- [x] Use verifier to check a tokens permission (Access private data?)
- [x] Add mock tests 
- [x] Implement this flow throughout ( in vaults)

**Comment by S-Coyle** [comment]
Closing - safe_authenticator now out of scope for this crate
