### ISSUE TITLE
Rustfmt options

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#1142]
Here are some rustfmt options which may be helpful:

```
use_try_shorthand = true

comment_width = 100
normalize_comments = true
wrap_comments = true

condense_wildcard_suffixes = true
format_strings = true
license_template_path = "license_template"
merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true
```

See the [full list of options](https://rust-lang.github.io/rustfmt/).

Currently most of them rely on unstable rustfmt, but they will be useful for making the code neater (for example, `merge_imports` for cleaning up imports and reducing lines of code).

**Comment by joshuef** [comment]
closing as we've gone monorepo now
