### ISSUE TITLE
Enable token deprecation / reissue

### ISSUE THREAD

**Issue by joshuef** [maidsafe/sn_client#1158]
It can happen that a user adjusts an applications permission, without immediately informing the app (and issuing a new token).

The ideal would be, presenting a deprecated token could immediately reissue a new token to an app.

This requires:

- [ ] Storage of tokens (#1157)
- [ ] Mark tokens as deprecated when updating app permissions from authenticator. (We likely need APIs for this, what exists and can that be repurposed for tokens?).
- [ ] at `ClientHandler` detect if a) current token is valid. and then if b) it's been marked as deprecated, respond with new token.
- [ ] Implement `Client` side handling of updated token response.

**Comment by S-Coyle** [comment]
Closing - safe_authenticator now out of scope for this crate
