### ISSUE TITLE
Fix append_only_data test in safe_app

### ISSUE THREAD

**Issue by Yoga07** [maidsafe/sn_client#1172]
Post initial implementation of AuthTokens, the append_only_data test [here](https://github.com/joshuef/safe_client_libs/blob/TokenUpdates/safe_app/src/tests/append_only_data.rs#L355) in safe_app tended to fail at the mpsc channels. This must be investigated and fixed before the milestone ends.

**Comment by S-Coyle** [comment]
Closing - safe_app now out of scope for this crate
