### ISSUE TITLE
Client does not time out when looking for network on its own port

### ISSUE THREAD

**Issue by b-zee** [maidsafe/sn_client#1404]
If the client binds its own qp2p port to the default (12000) and it's looking for a network on the default port (12000), it seems like the client does not time out while looking for the network (bootstrapping).

I've tried this with the `QuicP2pConfig.idle_timeout_msec` set to 5000 (5 seconds). Providing a hard coded contact with a different port (e.g. 12001), the client 'successfully' times out.

**Comment by joshuef** [comment]
ah, this should hopeflly get sorted w/ #1400 too now.
