### ISSUE TITLE
Useless code

### ISSUE THREAD

**Issue by Thierry61** [maidsafe/sn_client#1431]
https://github.com/maidsafe/sn_client/blob/d3c45a6ed8b991e723d78af7a1ebb541744f6db4/src/config_handler.rs#L54-L61

is equivalent to:
```rust
qp2p.local_port = Some(0);
```
because 0 is the value stored in `random_port_to_attempt`. If this is what was really intended then just replace the whole thing by this line.

But I suspect this wasn't the excepted result and in this case this issue is just a hint that there is something wrong in this piece of code.

**Comment by dirvine** [comment]
Yes clients need to always use a random port and never a known/guessable port. I think you are correct here, `Some(0)` is what we need. 
sn_node should also start on a random port for security, but clients will have weird timouts if we tried to use a fixed port for each endpoint establishment. 
cc @joshuef  @Yoga07  @lionel1704

**Comment by Thierry61** [comment]
Ok, setting port to 0 is done on purpose. I suggest that single line `qp2p.local_port = Some(0);` would be more explicit than current code, maybe with a comment explaining that value 0 is to get a random port.

In fact this issue was just to insure that this wasn’t a bug. I'll close it then.

**Comment by Thierry61** [comment]
Sorry, I reopen the issue. I think now that defined port in configuration file shouldn't be overridden in case the user wants to control it (for example this port has been specifically opened in firewall).

Random port should be used only in case it hasn't been defined in configuration (which should be None value).

**Comment by dirvine** [comment]
YEs the config items are being changed today, we won't override any config file settings, but should need very few of these. i.e. we should not switch igd on, it should automatically try unless explicitly switched off. Ports should be random unless manual port forward is used etc. 
We should update this today

**Comment by lionel1704** [comment]
The code block in discussion has been removed. If the user specifies a port number via the config it will be used, otherwise a random port will be used.
