### ISSUE TITLE
Implement simple key-value based MutableData storage for librdf

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/sn_client#704]
With complete Rust bindings for librdf (#703), implement a storage that will serialise RDF triples into keys and values stored in Mutable Data.
* A _storage_ is defined as a factory function that returns a set of function pointers expected by librdf (for an example refer to e.g. [librdf_storage_hashes_register_factory](https://github.com/dajobe/librdf/blob/692c93a3c64c5a7399b760f1b9012e13b2caec12/src/rdf_storage_hashes.c#L1934-L1962)).
* Reuse an existing implementation that [uses BerkeleyDB](http://librdf.org/docs/api/redland-storage-module-hashes.html) (a key-value storage) as the back-end.
* Instead of storing keys and values in a Mutable Data object directly, return them as a list. This way we can compose a [MutateMDataEntries](https://github.com/maidsafe/routing/blob/0081a48d59e4fe3fb86b20da1fceb8f757855112/src/messages/request.rs#L123-L135) request on the client side and make the RDF serialisation opaque for Vaults. Although this opaqueness can be undesired in several cases, this approach will allow us to have a basic support for RDF in SAFE Client Libs earlier and we'll be able to iterate on it quicker.

**Comment by lionel1704** [comment]
This has been implemented in lionel1704/safe_client_libs@026668a. The findings have been documented [in the redland-rs wiki](https://github.com/lionel1704/redland-rs/wiki/Findings-on-the-Redland-internal-implementation)
