### ISSUE TITLE
feature: NFS function to access dynamic file size while open for write

### ISSUE THREAD

**Issue by happybeing** [maidsafe/sn_client#719]
This is a feature request on the SAFE NFS emulation API.

When a file is opened for read the file size is accessible using `File.size()`

When a file is opened for write and only write `File.size()` returns an error, but if open for read _and_ write this will return the original size.

Suggested feature: add a method `File.size_written()` that returns the current size of a file that is open for write and/or read. I'm not sure if it should return zero or an error if the file is only open for read, but probably an error if the reason can be indicated.

This issue is raised as a result of the dev forum discussion [here](https://forum.safedev.org/t/safe-nfs-open-capabilities-and-restrictions/2233/5?u=happybeing).

**Comment by theWebalyst** [comment]
Another thing to consider which might affect implementation of this feature is whether to disallow a file being opened for both read and write simultaneously:

> "Thinking about this more, I wonder if this should even be allowed. It seems counterintuitive; a file opened for reading and writing will return a single file handle, but the Reader and Writer can have completely different contents. So you’d be using the same file handle for two different purposes which can be confusing and error-prone."
> 
> "There is also no performance benefit to simultaneous read/write since it’s basically two separate fetches in one call to file.open(). I think it would be better if we disallow opening a file for both read/write (make it an error case) and instead encourage two separate calls to file.open(). Then we can make file.size() work for files in write mode. Would like to hear what others think" - @m-cat ([ref](https://forum.safedev.org/t/safe-nfs-open-capabilities-and-restrictions/2233/6?u=happybeing))

**Comment by m-cat** [comment]
Need to wait for #732 to decide how to handle this.

**Comment by m-cat** [comment]
What does that confused emoji mean @theWebalyst ? 😄 If we can properly open a file for both reading and writing so that there are not two separate self_encryptor handles internally, then there would be no need for `size_written()` as there will only be one size. We can't do this now because there are two separate sizes: that of the data to be read, and that of the written data.

**Comment by theWebalyst** [comment]
Sorry @m-cat it was supposed to be a thumbs up!
