### ISSUE TITLE
Add DESCRIPTION for each job in Travis

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#726]
I noticed some projects using a `DESCRIPTION` environment variable to tag each job in Travis, making it more clear what the job is doing. It is a good way to indicate exactly what a job is doing -- for example, that it runs binary compatibility tests.

See [this `.travis.yml`](https://github.com/rust-random/rand/blob/master/.travis.yml#L62) for an example.

**Comment by nbaksalyar** [comment]
Great idea 👍
This should be merged as a part of https://github.com/maidsafe/safe_client_libs/pull/728

**Comment by m-cat** [comment]
Looks like that PR didn't include this change, so this Issue is still open.

**Comment by m-cat** [comment]
I forgot to mention in the OP the main benefit of doing this 🤦‍♂️ which is that the `DESCRIPTION` will appear next to each job in Travis.

Pictorial examplar: https://www.dropbox.com/s/d6noon1fxpisqk6/Screen%20Shot%202019-04-11%20at%204.44.16%20PM.png?dl=0

**Comment by S-Coyle** [comment]
Closing - main CI tool is now GH Actions
