### ISSUE TITLE
Add labels to Issues to encourage contributions

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#730]
Some of the existing Issues are low-hanging fruit and do not require much pre-existing knowledge of the libraries. We should tag such Issues to make the difficulty level clear (with e.g. `easy`) and to encourage new contributors (with e.g. `help-wanted`).

To see some example repositories and labels, this is a good list:

- https://github.com/MunGell/awesome-for-beginners

And we could reserve some Issues specifically for first-timers to get their feet wet:

- https://www.firsttimersonly.com/

**Comment by hunterlester** [comment]
Sticking this here as I'm referencing from many other repos.
[Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

**Comment by m-cat** [comment]
I went through all the existing Issues in this repo and classified the ones that are low-hanging fruit (there are only a couple). What remains is to create a process for tagging new Issues as they come in.
