### ISSUE TITLE
Remove instances of ",)" from the source code

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#734]
There are many instances of `,)` in the code, for example:

```rs
            let permission_set = *try_cb!(
                permissions
                    .get(&user,)
                    .ok_or(AppError::InvalidSignPubKeyHandle,),
                user_data,
                o_cb
            );
```
> [source](https://github.com/maidsafe/safe_client_libs/blob/master/safe_app/src/ffi/mutable_data/permissions.rs#L107)

It seems like this was introduced in [this commit](https://github.com/maidsafe/safe_client_libs/commit/1a26890ca211bc0380b095e6468f8a0107b24e06#diff-cb10b13dd46d46e4c660f331ed3d50a0R154) when we ran `rustfmt-nightly`. Running the latest version of `rustfmt` Stable doesn't fix this.

The fix is simply to do a search-replace for `,)` throughout the project, followed by running `cargo fmt` for good measure.

**Comment by trecement** [comment]
I will take a look at this

looks like 71 instances to sort
```
willie@gagarin:~/projects/maidsafe/client_libs/safe_client_libs$ grep -r -n ",)"|wc
     71     215    5028
```

trecement aka southside

**Comment by trecement** [comment]
is  ",)"    **always** wrong?`

I don't know enough rust to tell if this is syntactly incorrect
safe_core/src/utils/mod.rs:35:    ($($item:expr),*,) => {

and similarly on line 54 of the same file.

**Comment by m-cat** [comment]
Thanks for taking this issue! 

> I don't know enough rust to tell if this is syntactly incorrect
> safe_core/src/utils/mod.rs:35: ($($item:expr),*,) => {
>
> and similarly on line 54 of the same file.

Good question. These happen to be correct :) These are macro definitions, and the trailing comma allows optional trailing commas in usage of the macro -- see [this answer](https://stackoverflow.com/questions/43143327/how-to-allow-optional-trailing-commas-in-macros) for more info.

**Comment by trecement** [comment]
OK thats the replacements I think should be made completed

willie@gagarin:~/projects/maidsafe/client_libs/safe_client_libs$ cargo fmt
willie@gagarin:~/projects/maidsafe/client_libs/safe_client_libs$ grep -r -n ",)"Binary file safe-client-libs.png matches
Binary file .git/objects/pack/pack-d5434eb1b1636e8014d49739feb43f93ed1084c3.pack matches
Binary file .git/objects/pack/pack-d5434eb1b1636e8014d49739feb43f93ed1084c3.idx matches
.git/hooks/prepare-commit-msg.sample:30:#  ,|template,)
safe_core/src/utils/mod.rs:35:    ($($item:expr),*,) => {
safe_core/src/utils/mod.rs:54:    ($($key:expr => $value:expr),*,) => {


next I think I need to read a bit more about git other than git pull and git clone

**Comment by m-cat** [comment]
Let me know if you need any help with that, would be happy to walk you through the process of raising a PR!

**Comment by trecement** [comment]
THis is almost certainly the wrong way to do it

trecement/maidsafe_client_libs_issue_734

**Comment by trecement** [comment]
I give in....    I do need help with raising the PR properly

https://github.com/trecement/safe_client_libs/tree/trecement-issue734     <-- needs proper commit message

**Comment by m-cat** [comment]
Normally raising the PR is as simple as going to [the branch](https://github.com/trecement/safe_client_libs/tree/trecement-issue734) and clicking "Pull request", but it looks like you copied all the modified files to the root of the repository: [see here](https://github.com/maidsafe/safe_client_libs/compare/master...trecement:trecement-issue734?expand=1). So you'll have to fix this first -- let me know exactly what steps you took and I'll see if I can spot where things went wrong. Are you using the git command-line or a GUI?

**Comment by m-cat** [comment]
Hey @trecement , we recently updated the [Contribution guide](https://github.com/maidsafe/safe_client_libs/wiki/Guide-to-contributing#development) with some new sections and more links which may be helpful. Let me know if anything's not clear or if you need help.

Don't mean to badger you of course, take your time!

**Comment by clD11** [comment]
@m-cat was this ever resolved?

**Comment by clD11** [comment]
@lionel1704 Hi from other post I see @m-cat may not be working on this currently and suggested you as a contact.

Has this been resolved, I only see 3 hits when searching the code and they relate to macros so guessing its done
