### ISSUE TITLE
Refactor Client Libs to use impl Trait

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#738]
+ `impl Trait` is now available in Rust 1.26. Remove as many `Box`'s as possible.
+ Also re-scan code for better substitution of `ok!/err!/fry!` and `into_box` if possible.

[Original Jira task](https://maidsafe.atlassian.net/browse/MAID-1611)

**Comment by nbaksalyar** [comment]
`fut.boxed()` has been also deprecated in favour of `Box::new(fut)` now:
https://github.com/rust-lang-nursery/futures-rs/issues/228
