### ISSUE TITLE
Improve MockVault performance

### ISSUE THREAD

**Issue by oetyng** [maidsafe/sn_client#740]
From what I have seen, the vaults will write each chunk to its own file on disk.
MockVault however, writes to a single file. This is impacting IO performance significantly, and the testing utility for it when storing anything above a couple of thousand stored values, diminishes.

Would it be possible to redesign the MockVault implementation, to be closer to the actual implementation, so that chunks are written to individual files? It wouldn’t be very complicated or invasive it seems to me, and the change would be rather well contained, with few implications if any.

It would give a persistence mechanism that is as closely resembling the actual implementation as possible, and I think would increase the value of the tests.

The advantage of the single MockVault file is that it can be easily shared between machines, but the individual files could for example all be stored in a folder which can easily be zipped up.

**Comment by m-cat** [comment]
Thanks for the submission! It sounds like a reasonable idea to me.

I think this will require benchmarks to make sure we don't introduce a performance regression (e.g. if there are thousands of chunks then there could be thousands of files, which could inadvertently introduce new performance problems if not implemented properly).

**Comment by oetyng** [comment]
Yes, that's true. I was hoping that maybe we could get so close to the real implementation, that if we actually do find performance problems, it could perhaps be valuable insight for the real implementation as well. 

The performance problem with single file is mostly about the contention with heavy writing. I think the reverse might be true if reading many files. I'm not all that familiar with how the access pattern will look like in a real vault, and how it might differ from a mock vault. I need to read up more on what's going on there.

**Comment by m-cat** [comment]
Yep, agreed. I meant to mention above that I think more benchmarks would be really useful to have anyway, especially since we don't have too many in Safe Client Libs yet.
