### ISSUE TITLE
Refactor test_utils modules in safe_auth and safe_app

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#746]
It seems like several functions in [safe_app::test_utils.rs](https://github.com/maidsafe/safe_client_libs/blob/master/safe_app/src/test_utils.rs) are not specific to safe_app, and in fact are often duplicated in safe_authenticator tests. Three that jump out at me are `create_auth_req`, `create_random_auth_req`, and `create_auth_req_with_access`, but there may be more.

Should we perhaps look into moving applicable functions that are not auth- or app-specific into a common module in `safe_core`?

**Comment by m-cat** [comment]
We should also look into inconsistencies with the `run` functions in the `test_utils` modules. Specifically, `run` in safe_app is equivalent to the differently-named `try_run` in safe_auth, but `run_now` in safe_app is different from `run` in safe_auth. Naming inconsistencies aside, why are there seemingly two different schemes for running test clients in safe_auth and safe_app?

**Comment by S-Coyle** [comment]
Closing - safe_app and safe_authenticator now not in the scope of this crate
