### ISSUE TITLE
Remove unwraps from package.rs

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#753]
Unwraps are probably not a huge deal in `package.rs`, but it would be rather easily to remove them (which would certainly make the code more concise). We can replace them with `?` and make `main` return a generic `Result`. This will return a non-0 error code so that the packaging step should gracefully fail. See [here](https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/question-mark-in-main-and-tests.html) for more info.

Also check if there are any other instances of `.unwrap()` which can be removed (the `unwrap!` macro is fine in tests and in places where the unwrap logically cannot fail).

**Comment by S-Coyle** [comment]
`unwrap` now removed
