### ISSUE TITLE
Improve documentation in SAFE Core, Authenticator, and App

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#773]
For SAFE Core, Authenticator, and App:

1. Improve module-level documentation, providing a high-level description of the crates (e.g. now it says just "SAFE App" or "SAFE Authenticator" and nothing more), stating its purpose and primary functions.

2. Check the documentation for individual public functions and improve it where needed. E.g., describe what a function does instead of just reiterating its name or describing how it works. Also provide documentation for function parameters.

**Comment by S-Coyle** [comment]
Closing legacy issue - documentation will be focused on in due course and an issue created for that when appropriate.
