### ISSUE TITLE
MockVault location permission denied error when switching users (linux)

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#778]
After initially creating MockVault as one user, attempting to write MockThings as another user fails with permission denied. Parhaps move mock location? Or create on a per user basis? (though perhaps annoying if attempting to dev something...)

As noted: https://forum.safedev.org/t/problem-with-testing-peruse-v0-6-0-and-web-api-playground-3-0/1786

> I did get OS error code 13: “permission denied” when trying to create a new account in Peruse.
After a bit of looking I solved this problem by removing /tmp/MockVault (created by first user, so ‘access denied’ for second user…)

**Comment by joshuef** [comment]
we no longer have/use a mockvault, going to close this as we've shifted over to a monorepo: https://github.com/maidsafe/safe_network
