### ISSUE TITLE
Released system_uri file for linux has execution access rights

### ISSUE THREAD

**Issue by bochaco** [maidsafe/sn_client#780]
Unziping the `system_uri.so` fetched from S3 (https://s3.eu-west-2.amazonaws.com/system-uri/system_uri-v0.4.0-linux-x64.zip), shows that it has execution access rights:
```bash
-rwxr-xr-x  1 bochaco bochaco 6035920 Jan 16  2018 libsystem_uri.so
```

I presume it shouldn't.

**Comment by S-Coyle** [comment]
Closing - no longer relevant
