### ISSUE TITLE
Client refactor: get rid of contexts and add `Run` trait

### ISSUE THREAD

**Issue by m-cat** [maidsafe/sn_client#794]
Instead of implementing both `send` and `run` separately for `Authenticator` and `App`, we could implement them a single time in a `Run` trait. Something like this implementation on the following branch should work, with enough effort:

https://github.com/m-cat/safe_client_libs/blob/run-refactor/safe_core/src/lib.rs#L165

We can simplify this further by not requiring to pass the context all the time. Instead, we might use something like `thread_local!` vars.

We could also investigate getting rid of contexts altogether and stuffing that information into the `AppInner` struct, or getting rid of `AuthInner` and `AppInner` and putting that information into the respective contexts.

**Comment by nbaksalyar** [comment]
Related to https://github.com/maidsafe/safe_client_libs/issues/924 and can be implemented along with that task.

**Comment by S-Coyle** [comment]
Closing - safe_app and safe_authenticator now out of scope for this crate
