### ISSUE TITLE
Small optimization in object_cache.rs

### ISSUE THREAD

**Issue by sprucely** [maidsafe/sn_client#920]
I noticed in safe_app in object_cache.rs that the macro impl_cache makes use of `Option::ok_or` rather than `Option::ok_or_else`. Doesn't this cause an allocation of the given `AppError::$error` even when no error will be returned? It'd be a trivial change to use ok_or_else to only instantiate the error when necessary.

**Comment by S-Coyle** [comment]
closing - safe_app no longer in scope of this crate
