### ISSUE TITLE
Remove Permission type in safe_core/ipc

### ISSUE THREAD

**Issue by Yoga07** [maidsafe/sn_client#971]
This Permission type is redundant. https://github.com/maidsafe/safe_client_libs/blob/97baefd38965b7a0bc5cdb62f76611b9df8dd90b/safe_core/src/ipc/req/mod.rs#L48 It was introduced only for the purpose of distinguishing between the Mutable Data permissions and the container permissions. The latter is a higher-level construct referring to the apps permissions for accessing the user's containers (like music, videos, etc.) and read permissions referred to app having the encryption key to read the data. However, we didn't have the read perm for MutableData because it was implied it's always public: hence the distinct permission type.

Now that we have an opposite situation (MutableData is always unpublished), can we  just use MDataPermissionSet in this context without requiring any conversions?

Concern raised by: @nbaksalyar

**Comment by m-cat** [comment]
Would be nice to wait and make this change once the `MDataPermissionSet` FFI equivalent is available in `safe-nd`, once the FFI is implemented there. That way we don't have to maintain the `FfiPermissionSet` in SCL any more.

**Comment by joshuef** [comment]
safe_core hasn't existed for a while. This issue is out of date, closing
