### ISSUE TITLE
Investigate why safe_app tests can run slow with on-disk mock vault storage

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/sn_client#996]
Sometimes the safe_app tests can run so slow they time out during the entire test suite run.

There are several possible causes for that, but it's worth starting with one of these:
1. The Vault locking logic is inefficient.
2. The storage itself gets overflowed and causes the slowdowns.

**Comment by S-Coyle** [comment]
closing - safe_app no longer in scope of this crate
